-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 21:38:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet-tech
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projet-tech` ;

-- -----------------------------------------------------
-- Schema projet-tech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet-tech` DEFAULT CHARACTER SET utf8 ;
USE `projet-tech` ;

-- -----------------------------------------------------
-- Table `projet-tech`.`promos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`promos` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`promos` (
  `idpromos` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idpromos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`user` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `mail` VARCHAR(200) NULL,
  `password` VARCHAR(255) NULL,
  `date_de_naissance` DATE NULL,
  `type` INT NULL,
  `description` VARCHAR(200) NULL,
  `ville` VARCHAR(200) NULL,
  `interests` VARCHAR(45) NULL,
  `photo` VARCHAR(200) NULL,
  `isvalide` TINYINT NULL,
  `idpromos` INT NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_promos1_idx` (`idpromos` ASC) VISIBLE,
  CONSTRAINT `fk_user_promos1`
    FOREIGN KEY (`idpromos`)
    REFERENCES `projet-tech`.`promos` (`idpromos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`reactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`reactions` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`reactions` (
  `idreactions` INT NOT NULL AUTO_INCREMENT,
  `type` TINYINT NULL,
  PRIMARY KEY (`idreactions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`post` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`post` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `postcol1` VARCHAR(45) NULL,
  `postcol` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `titre` VARCHAR(45) NULL,
  `contenu` VARCHAR(200) NULL,
  `date` DATETIME NULL,
  `lieu` VARCHAR(200) NULL,
  `photo` VARCHAR(45) NULL,
  `nblike` INT NULL,
  `nbdislike` INT NULL,
  `for` INT NULL DEFAULT 0,
  `iduser` INT NOT NULL,
  `idreactions` INT NOT NULL,
  PRIMARY KEY (`idpost`),
  INDEX `fk_post_user1_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_post_reactions1_idx` (`idreactions` ASC) VISIBLE,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `projet-tech`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_reactions1`
    FOREIGN KEY (`idreactions`)
    REFERENCES `projet-tech`.`reactions` (`idreactions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`amis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`amis` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`amis` (
  `idamis` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `statut` TINYINT NULL,
  PRIMARY KEY (`idamis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`message` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`message` (
  `idmessage` INT NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(200) NULL,
  `date` DATETIME NULL,
  `iduser` INT NOT NULL,
  `idamis` INT NOT NULL,
  PRIMARY KEY (`idmessage`),
  INDEX `fk_message_user_idx` (`iduser` ASC) VISIBLE,
  INDEX `fk_message_amis1_idx` (`idamis` ASC) VISIBLE,
  CONSTRAINT `fk_message_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `projet-tech`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_amis1`
    FOREIGN KEY (`idamis`)
    REFERENCES `projet-tech`.`amis` (`idamis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
