-- MySQL Script generated by MySQL Workbench
-- Tue Mar 28 20:54:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet-tech
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projet-tech` ;

-- -----------------------------------------------------
-- Schema projet-tech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet-tech` DEFAULT CHARACTER SET utf8 ;
USE `projet-tech` ;

-- -----------------------------------------------------
-- Table `projet-tech`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`user` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `mail` VARCHAR(200) NULL,
  `password` VARCHAR(255) NULL,
  `date_de_naissance` DATE NULL,
  `type` INT NULL,
  `description` VARCHAR(200) NULL,
  `ville` VARCHAR(200) NULL,
  `interests` VARCHAR(45) NULL,
  `photo` VARCHAR(200) NULL,
  `isvalide` TINYINT NULL,
  `token` VARCHAR(255) NULL,
  `inactive_time` DATETIME NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`promos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`promos` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`promos` (
  `idpromos` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idpromos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`post` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`post` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL,
  `titre` VARCHAR(45) NULL,
  `contenu` VARCHAR(200) NULL,
  `date` DATETIME NULL,
  `photo` VARCHAR(255) NULL,
  `for` INT NULL DEFAULT 0,
  `link` VARCHAR(255) NULL,
  `interets` VARCHAR(255) NULL,
  `etiquette` VARCHAR(255) NULL,
  PRIMARY KEY (`idpost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`message` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`message` (
  `idmessage` INT NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(200) NULL,
  `date` DATETIME NULL,
  `iduser` INT NOT NULL,
  `idamis` INT NOT NULL,
  PRIMARY KEY (`idmessage`),
  INDEX `fk_message_user_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_message_user`
    FOREIGN KEY (`iduser`)
    REFERENCES `projet-tech`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`likes` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`likes` (
  `idlikes` INT NOT NULL AUTO_INCREMENT,
  `type` INT NULL DEFAULT 0,
  `idpost` INT NOT NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idlikes`, `iduser`),
  INDEX `fk_reactions_post1_idx` (`idpost` ASC) VISIBLE,
  INDEX `fk_likes_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_reactions_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `projet-tech`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `projet-tech`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`admin` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `nameAdmin` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`post_has_admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`post_has_admin` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`post_has_admin` (
  `idpost` INT NOT NULL,
  `idadmin` INT NOT NULL,
  PRIMARY KEY (`idpost`, `idadmin`),
  INDEX `fk_post_has_Admin_Admin1_idx` (`idadmin` ASC) VISIBLE,
  INDEX `fk_post_has_Admin_post1_idx` (`idpost` ASC) VISIBLE,
  CONSTRAINT `fk_post_has_Admin_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `projet-tech`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_Admin_Admin1`
    FOREIGN KEY (`idadmin`)
    REFERENCES `projet-tech`.`admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`post_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`post_user` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`post_user` (
  `iduser` INT NOT NULL,
  `idpost` INT NOT NULL,
  PRIMARY KEY (`iduser`, `idpost`),
  INDEX `fk_user_has_post_post1_idx` (`idpost` ASC) VISIBLE,
  INDEX `fk_user_has_post_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_post_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `projet-tech`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_post_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `projet-tech`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`user_has_amis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`user_has_amis` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`user_has_amis` (
  `iduser` INT NOT NULL,
  `idamis` INT NOT NULL,
  `statut` INT NULL,
  PRIMARY KEY (`iduser`, `idamis`),
  INDEX `fk_user_has_amis_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_amis_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `projet-tech`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`lieu` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`lieu` (
  `idlieu` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  PRIMARY KEY (`idlieu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`post_has_lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`post_has_lieu` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`post_has_lieu` (
  `idlieu` INT NOT NULL,
  `idpost` INT NOT NULL,
  PRIMARY KEY (`idlieu`, `idpost`),
  INDEX `fk_lieu_has_post_post1_idx` (`idpost` ASC) VISIBLE,
  INDEX `fk_lieu_has_post_lieu1_idx` (`idlieu` ASC) VISIBLE,
  CONSTRAINT `fk_lieu_has_post_lieu1`
    FOREIGN KEY (`idlieu`)
    REFERENCES `projet-tech`.`lieu` (`idlieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lieu_has_post_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `projet-tech`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`notification` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`notification` (
  `idnotification` INT NOT NULL AUTO_INCREMENT,
  `idetiquette` VARCHAR(45) NULL,
  `idpost` INT NOT NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idnotification`, `idpost`, `iduser`),
  INDEX `fk_notification_post1_idx` (`idpost` ASC) VISIBLE,
  INDEX `fk_notification_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_notification_post1`
    FOREIGN KEY (`idpost`)
    REFERENCES `projet-tech`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `projet-tech`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet-tech`.`user_has_promos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet-tech`.`user_has_promos` ;

CREATE TABLE IF NOT EXISTS `projet-tech`.`user_has_promos` (
  `iduser` INT NOT NULL,
  `idpromos` INT NOT NULL,
  `statut` INT NULL,
  PRIMARY KEY (`iduser`, `idpromos`),
  INDEX `fk_user_has_promos_promos1_idx` (`idpromos` ASC) VISIBLE,
  INDEX `fk_user_has_promos_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_promos_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `projet-tech`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_promos_promos1`
    FOREIGN KEY (`idpromos`)
    REFERENCES `projet-tech`.`promos` (`idpromos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
